[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/generate"
  [headers.values]
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        Cross-Origin-Resource-Policy = "cross-origin"
        Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/mgenerate"
  [headers.values]
      Cross-Origin-Opener-Policy = "same-origin"
      Cross-Origin-Embedder-Policy = "require-corp"
      Cross-Origin-Resource-Policy = "cross-origin"
      Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/ngenerate"
  [headers.values]
      Cross-Origin-Opener-Policy = "same-origin"
      Cross-Origin-Embedder-Policy = "require-corp"
      Cross-Origin-Resource-Policy = "cross-origin"
      Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/bgenerate"
  [headers.values]
      Cross-Origin-Opener-Policy = "same-origin"
      Cross-Origin-Embedder-Policy = "require-corp"
      Cross-Origin-Resource-Policy = "cross-origin"
      Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/workers/*"
  [headers.values]
      Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-max-age=604800"


    

    
